export const CLEAR_IMAGE_EDITOR = 'CLEAR_IMAGE_EDITOR';
export const EDIT_PRODUCT_GROUP_IMAGES = 'EDIT_PRODUCT_GROUP_IMAGES';

export const SAVE_PRODUCT_GROUP_IMAGES = 'SAVE_PRODUCT_GROUP_IMAGES';
export const START_SAVING_PRODUCT_GROUP_IMAGES = 'START_SAVING_PRODUCT_GROUP_IMAGES';
export const SUCCESS_SAVING_PRODUCT_GROUP_IMAGES = 'SUCCESS_SAVING_PRODUCT_GROUP_IMAGES';
export const ERROR_SAVING_PRODUCT_GROUP_IMAGES = 'ERROR_SAVING_PRODUCT_GROUP_IMAGES';

export const GET_RECOMMENDED_IMAGES = 'GET_RECOMMENDED_IMAGES';
export const START_LOADING_RECOMMENDED_IMAGES = 'START_LOADING_RECOMMENDED_IMAGES';
export const SUCCESS_LOADING_RECOMMENDED_IMAGES = 'SUCCESS_LOADING_RECOMMENDED_IMAGES';
export const ERROR_LOADING_RECOMMENDED_IMAGES = 'ERROR_LOADING_RECOMMENDED_IMAGES';

export const SET_REJECTED_FILES = 'SET_REJECTED_FILES';
export const UPDATE_HAVE_MAXIMUM_IMAGES_COUNT = 'UPDATE_HAVE_MAXIMUM_IMAGES_COUNT';
