export const POLLING_ONLINE_STORE_IMPORT_STATUS = 'POLLING_ONLINE_STORE_IMPORT_STATUS';
export const START_ONLINE_STORE_IMPORT = 'START_ONLINE_STORE_IMPORT';
export const FINISH_ONLINE_STORE_IMPORT = 'FINISH_ONLINE_STORE_IMPORT';
